FROM php:7.2-cli

RUN apt-get update && apt-get install -y libicu-dev git libz-dev wget nano libpng-dev libcurl4-openssl-dev vim netcat  \
    && rm -rf /var/lib/apt/lists/*r

RUN docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd && docker-php-ext-install pdo_mysql
RUN docker-php-ext-install intl opcache zip mbstring gd sockets bcmath

COPY ./docker/web/entrypoint-cli.sh /usr/bin/entrypoint-cli.sh
RUN chmod +x /usr/bin/entrypoint-cli.sh

ENTRYPOINT ["entrypoint-cli.sh"]
CMD ["php", "-a"]