old_sound_rabbit_mq:
    connections:
        default:
            host:     'rabbit'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
    producers:
        create_order:
            connection:       default
            exchange_options: {name: 'order', type: direct}
        create_complain:
            connection:       default
            exchange_options: {name: 'complain', type: direct}
    consumers:
        create_order:
            connection:       default
            exchange_options: {name: 'order', type: direct}
            queue_options:    {name: 'order'}
            callback:         rst.consumer.order
        create_complain:
            connection:       default
            exchange_options: {name: 'complain', type: direct}
            queue_options:    {name: 'complain'}
            callback:         rst.consumer.complain